version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
    links:
      - php
  php:
    build: ./images/php
    links:
      - mysql
    volumes:
      - ./www:/var/www
    environment:
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: "client_host=host.docker.internal"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sait
  mongo:
    image: mongo
    ports:
      - 27017:27017
  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '!Password!'
    ports:
      - "1433:1433"
    volumes:
      - ./shared-volume:/var/opt/mssql/shared-volume
    restart: unless-stopped 